# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: gabrielmagno1@gmail.com
author_name: Gabriel Magno
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: theme
labextension_name: catppuccin-jupyterlab
mimetype: ''
mimetype_name: ''
project_short_description: 📊 Soothing pastel theme for JupyterLab.
python_name: catppuccin-jupyterlab
repository: https://github.com/gabrielmagno/jupyterlab
test: false
viewer_name: ''

